/* Effacer les anciennes valeurs */
DELETE FROM JOUR_SERVICE;
DELETE FROM NOTIF_ADMIN;
DELETE FROM MOT_SERVICE;
DELETE FROM MOT_BIEN;
DELETE FROM NOTIF;
DELETE FROM PHOTO;
DELETE FROM TAXONOMIE;
DELETE FROM CONSOMMATION;
DELETE FROM JOUR;
DELETE FROM SERVICES;
DELETE FROM BIEN;
DELETE FROM MEMBRES;
 
/* Insertion des nouvelles valeurs */
